src/Entity/Store/Brand.php
<?php

namespace App\Entity\Store;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Store\BrandRepository")
 * @ORM\Table(name="sto_brand")
 */
class Brand
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Store\Product", mappedBy="brand")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setBrand($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getBrand() === $this) {
                $product->setBrand(null);
            }
        }

        return $this;
    }
}

src/Entity/Store/Color.php
<?php

namespace App\Entity\Store;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Store\ColorRepository")
 * @ORM\Table(name="sto_color")
 */
class Color
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/Store/Image.php
<?php

namespace App\Entity\Store;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Store\ImageRepository")
 * @ORM\Table(name="sto_image")
 */
class Image
{
    public const PUBLIC_DIR = 'img/products/';

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $alt;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getAlt(): string
    {
        return $this->alt;
    }

    public function setAlt(string $alt): self
    {
        $this->alt = $alt;

        return $this;
    }

    public function getPublicPath(): string
    {
        return self::PUBLIC_DIR.$this->url;
    }
}

src/Entity/Store/Product.php
<?php

namespace App\Entity\Store;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\Store\ProductRepository")
 * @ORM\Table(name="sto_product")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="text")
     */
    private $longDescription;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Store\Image", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false, name="sto_image_id")
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Store\Brand", inversedBy="products")
     * @ORM\JoinColumn(nullable=false, name="sto_brand_id")
     */
    private $brand;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Store\Color")
     * @ORM\JoinTable(
     *     name="sto_product_color",
     *     joinColumns={
     *         @ORM\JoinColumn(name="sto_product_id", nullable=false)
     *     },
     *     inverseJoinColumns={
     *         @ORM\JoinColumn(name="sto_color_id", nullable=false)
     *     },
     * )
     */
    private $colors;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
        $this->colors = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getLongDescription(): ?string
    {
        return $this->longDescription;
    }

    public function setLongDescription(string $longDescription): self
    {
        $this->longDescription = $longDescription;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getImage(): ?Image
    {
        return $this->image;
    }

    public function setImage(Image $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    /**
     * @return Collection|Color[]
     */
    public function getColors(): Collection
    {
        return $this->colors;
    }

    public function addColor(Color $color): self
    {
        if (!$this->colors->contains($color)) {
            $this->colors[] = $color;
        }

        return $this;
    }

    public function removeColor(Color $color): self
    {
        if ($this->colors->contains($color)) {
            $this->colors->removeElement($color);
        }

        return $this;
    }
}

src/Controller/StoreController.php
<?php

namespace App\Controller;

use App\Repository\Store\BrandRepository;
use App\Repository\Store\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/store", name="store_")
 */
class StoreController extends AbstractController
{
    /** @var ProductRepository */
    private ProductRepository $productRepository;

    /** @var BrandRepository */
    private BrandRepository $brandRepository;

    public function __construct(ProductRepository $productRepository, BrandRepository $brandRepository)
    {
        $this->productRepository = $productRepository;
        $this->brandRepository = $brandRepository;
    }
    /**
     * @Route("", name="list")
     */
    public function list(): Response
    {
        return $this->render('store/list.html.twig', [
            'products' => $this->productRepository->findAll(),
            'brands' => $this->brandRepository->findBy([], ['name' => 'ASC']),
        ]);
    }

    /**
     * @Route("/product/{id}/details/{slug}", name="product", requirements={"id" = "\d+"})
     */
    public function product(int $id, string $slug): Response
    {
        $product = $this->productRepository->find($id);
        if (null === $product) {
            throw new NotFoundHttpException();
        }

        if ($product->getSlug() !== $slug) {
            return $this->redirectToRoute('store_product', [
                'id' => $id,
                'slug' => $product->getSlug(),
            ], Response::HTTP_MOVED_PERMANENTLY);
        }

        return $this->render('store/product.html.twig', [
            'product' => $product,
            'brands' => $this->brandRepository->findBy([], ['name' => 'ASC']),
        ]);
    }
}

templates/store/list.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Nos produits | {{ parent() }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Nos marques</p>
            <div class="list-group">
                <a href="{{ path('store_list') }}" class="list-group-item active">Toutes les marques</a>
                {% for brand in brands %}
                    <a href="#" class="list-group-item">{{ brand.name }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-9">
            <p class="lead">Nos produits " Toutes les marques "</p>
            <div class="row text-center">
                {% for product in products %}
                    <div class="col-md-4 col-sm-6 hero-feature">
                        <div class="thumbnail">
                            <img src="{{ asset(product.image.publicPath) }}" alt="{{ product.image.alt }}">
                            <div class="caption">
                                <h3>{{ product.name|capitalize }}</h3>
                                <p>{{ product.description }}</p>
                                <p>
                                    <span class="badge">{{ product.price|format_currency('EUR') }}</span>
                                    <a href="{{ path('store_product', {'id': product.id, 'slug': product.slug}) }}" class="btn btn-default">Voir la fiche</a>
                                </p>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="alert alert-warning">
                        Il n'y aucun produit ici...
                    </div>
                {% endfor %}
            </div>

            <div class="row text-center">
                <nav>
                    <ul class="pagination pagination-lg">
                        <li>
                            <a href="#" aria-label="Précédent">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        <li class="active">
                            <a href="#">1</a>
                        </li>
                        <li>
                            <a href="#">2</a>
                        </li>
                        <li>
                            <a href="#">3</a>
                        </li>
                        <li>
                            <a href="#">4</a>
                        </li>
                        <li>
                            <a href="#">5</a>
                        </li>
                        <li>
                            <a href="#" aria-label="Suivant">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock %}

templates/store/product.html.twig
{% extends 'layout.html.twig' %}

{% block title %}{{ product.name|capitalize }} | {{ parent() }}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Nos marques</p>
            <div class="list-group">
                <a href="{{ path('store_list') }}" class="list-group-item">Toutes les marques</a>
                {% for brand in brands %}
                    <a href="#" class="list-group-item {{ product.brand.id is same as(brand.id) ? 'active' }}">{{ brand.name }}</a>
                {% endfor %}
            </div>
        </div>

        <div class="col-md-9">
            <p class="lead">
                Fiche descriptive "{{ product.name|capitalize }}"
                <a href="{{ path('store_list') }}" class="btn btn-default pull-right">Retour aux produits</a>
            </p>
            <div class="row">
                <div class="thumbnail">
                    <img class="img-responsive" src="{{ asset(product.image.publicPath) }}" alt="{{ product.image.alt }}">
                    <div class="caption-full">
                        <h4 class="pull-right"><span class="badge">{{ product.price|format_currency('EUR') }}</span></h4>
                        <h3>{{ product.name|capitalize }}</h3>
                        <p>{{ product.description }}</p>
                        <p>
                            {{ product.longDescription }}
                        </p>
                        {% for color in product.colors %}
                            <span class="label label-info">{{ color.name }}</span>
                        {% endfor %}
                    </div>
                </div>

                <div class="well">
                    <p class="pull-right label label-success">Actuellement 3 avis</p>
                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-info">Prénom Nom</span>
                            <span class="label label-default pull-right">28/01/2015</span>
                            <p>Un commentaire sur le produit, rédigé par un client, sera affiché à cet endroit.</p>
                        </div>
                    </div>

                    <hr/>

                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-info">Prénom Nom</span>
                            <span class="label label-default pull-right">28/01/2015</span>
                            <p>Un commentaire sur le produit, rédigé par un client, sera affiché à cet endroit.</p>
                        </div>
                    </div>

                    <hr/>

                    <div class="row">
                        <div class="col-md-12">
                            <span class="label label-info">Prénom Nom</span>
                            <span class="label label-default pull-right">28/01/2015</span>
                            <p>Un commentaire sur le produit, rédigé par un client, sera affiché à cet endroit.</p>
                        </div>
                    </div>

                    <hr/>

                    <div>
                        <form>
                            <div class="form-group">
                                <label for="name">Votre nom</label>
                                <input type="text" class="form-control" id="name">
                            </div>
                            <div class="form-group">
                                <label for="message">Votre avis</label>
                                <textarea class="form-control" name="comment" rows="3"></textarea>
                            </div>
                            <button type="submit" class="btn btn-info">Envoyer mon avis</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}